title: Alex Wechuli
show_downloads: True
remote_theme: pages
description: Creating machine learning models using linear regression model
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 
